# Generated by Django 4.2.5 on 2023-09-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reizan_type',
        ),
        migrations.CreateModel(
            name='TipB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(help_text='قیمت تیپ B محصول را به تومان وارد کنید', verbose_name='قیمت تیپ B محصول')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipB', to='product_app.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قیمت تیپ B محصول',
                'verbose_name_plural': 'قیمت تیپ B محصولات',
            },
        ),
    ]
