# Generated by Django 4.2.5 on 2023-12-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(help_text='۱۲۰ کاراکتر', max_length=120, null=True),
        ),
    ]
