# Generated by Django 4.2.5 on 2023-09-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_remove_product_reizan_type_tipb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(db_index=True, help_text='قیمت را به تومان وارد کنید', verbose_name='قیمت اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_index=True, help_text='۱۰۰کاراکتر مجاز است', max_length=150, verbose_name='اسم محصول'),
        ),
    ]
