# Generated by Django 4.2.5 on 2024-01-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_alter_bannersectionone_img_and_more'),
        ('product_app', '0002_basecategory_img_category_icon_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='اندازه تصویر : 400 × 400', null=True, upload_to='category', verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brands', to='home_app.sliderlogo', verbose_name='اسم برند'),
        ),
    ]
