# Generated by Django 4.2.5 on 2024-03-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disable_order',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن گزینه , امکان ثبت سفارش محصول غیرفعال میشود', verbose_name='ثبت سفارش غیرفعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selected_product',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن گزینه ، این محصول در بخش محصولات برگزیده نمایش داده می شود', verbose_name='محصول برگزیده'),
        ),
    ]
