# Generated by Django 4.2.5 on 2024-04-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_product_disable_order_alter_product_selected_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_product',
            field=models.PositiveIntegerField(default=5, help_text='تعداد محصول موجود و قابل سفارش', verbose_name='تعداد محصول'),
        ),
    ]
