# Generated by Django 4.2.5 on 2023-10-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_remove_product_best_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='product_app.tag', verbose_name='تگ ها'),
        ),
    ]
