# Generated by Django 4.2.5 on 2023-10-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, db_index=True, help_text='۱۵۰ کاراکتر مجاز است - optional', max_length=150, null=True, verbose_name='اسم محصول به انگلیسی'),
        ),
    ]
