# Generated by Django 4.2.5 on 2023-10-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_product_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت محصول'),
        ),
    ]
