# Generated by Django 4.2.5 on 2023-11-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selected_product',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن گزینه،این محصول در بخش محصولات برگزیده نمایش داده می شود', verbose_name='محصول برگزیده'),
        ),
    ]
