# Generated by Django 4.2.5 on 2023-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_product_selected_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.ImageField(help_text='حداقل سایز تصاویر 600x700 پیکسل باشد', upload_to='product', verbose_name='عکس محصول'),
        ),
    ]
