# Generated by Django 4.2.5 on 2023-11-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_alter_productimage_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(help_text='قیمت تیپ A محصول ریزان الکتریک را به تومان وارد کنید', verbose_name='قیمت تیپ A محصول')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipA', to='product_app.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قیمت تیپ A محصول',
                'verbose_name_plural': 'قیمت تیپ A محصولات',
            },
        ),
        migrations.DeleteModel(
            name='TipB',
        ),
    ]
