# Generated by Django 4.2.1 on 2023-09-08 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('situation', models.BooleanField(default=False, help_text='درصورت اینکه پیام بررسی شده گزینه را فعال کنید', verbose_name='وضعیت بررسی پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ دریافت پیام')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('file', models.FileField(blank=True, null=True, upload_to='messages_file', verbose_name='فایل')),
                ('submit', models.BooleanField(default=True, help_text='درصورت غیرفعال بودن ایمیل ارسال نمی شود.', verbose_name='ارسال ایمیل')),
                ('send_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('submit_status', models.BooleanField(blank=True, null=True, verbose_name='وضعیت ارسال پیام')),
                ('contact_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='contact_app.contactus', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'ارسال پیام به کاربر',
                'verbose_name_plural': 'ارسال پیام به کاربران',
            },
        ),
    ]
