# Generated by Django 4.2.5 on 2023-11-22 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_app', '0003_alter_sendemail_file_alter_sendemail_submit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
