# Generated by Django 4.2.5 on 2023-09-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='product_discount',
        ),
        migrations.AddField(
            model_name='productorder',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
    ]
