# Generated by Django 4.2.5 on 2023-09-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_remove_productorder_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='productorder',
            name='product_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت محصول'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='is_sms_sent',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='اس ام اس ارسال شده'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='هزینه کل'),
        ),
    ]
