# Generated by Django 4.2.1 on 2023-09-08 10:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='عنوان')),
                ('description', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('img', models.ImageField(blank=True, help_text='اندازه تصویر 700x650px باشد', null=True, upload_to='blog_image', verbose_name='تصویر')),
                ('status', models.BooleanField(default=True, help_text='درصورت غیرفعال بودن در سایت انتشار نمی یابد', verbose_name='وضعیت انتشار')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='این فیلد به صورت خودکار تکمیل می شود', unique=True, verbose_name='اسلاگ')),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('blog', models.ForeignKey(help_text='کامنت مدنظر برای کدام مقاله است', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.blog', verbose_name='مقاله')),
                ('parent', models.ForeignKey(blank=True, help_text='اگر این کامنت درجواب کامنت دیگری باشد تکمیل میگردد', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog_app.comment', verbose_name='جواب کامنت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ('-created_at',),
            },
        ),
    ]
