# Generated by Django 4.2.5 on 2023-10-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی'),
        ),
    ]
