# Generated by Django 4.2.5 on 2024-01-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, help_text='822 × 522 px', null=True, upload_to='blog_image', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.BooleanField(default=True, help_text='درصورت غیرفعال بودن در سایت انتشار نمی یابد'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='250 کاراکتر', max_length=250, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.blog', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog_app.comment', verbose_name='جواب کامنت'),
        ),
    ]
