# Generated by Django 4.2.5 on 2024-01-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blog_created_at_alter_blog_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, help_text='اندازه تصویر : 522 × 822', null=True, upload_to='blog_image', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(help_text='150 کاراکتر', max_length=150, null=True),
        ),
    ]
