# Generated by Django 4.2.5 on 2023-09-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='شماره موبایل'),
        ),
    ]
