# Generated by Django 4.2.1 on 2023-09-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderbannerimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sliderbannerimage',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='sliderbannerimage',
            name='title',
        ),
        migrations.AddField(
            model_name='sliderbannerimage',
            name='category_id',
            field=models.SmallIntegerField(blank=True, help_text='ID دسته بندی مربوط به این تصویر را وارد کنید', null=True, verbose_name='ID دسته بندی تصویر '),
        ),
        migrations.AddField(
            model_name='sliderbannerimage',
            name='category_slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='اسلاگ دسته بندی را که مربوط به این تصویر است را وارد کنبد', null=True, verbose_name='اسلاگ دسته بندی تصویر'),
        ),
        migrations.AlterField(
            model_name='bannersectionone',
            name='category_id',
            field=models.SmallIntegerField(help_text='ID دسته بندی مربوط به این تصویر را وارد کنید', verbose_name='ID دسته بندی تصویر '),
        ),
    ]
