# Generated by Django 4.2.5 on 2024-01-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusfeature',
            name='about_us',
        ),
        migrations.DeleteModel(
            name='BannerSectionTwo',
        ),
        migrations.DeleteModel(
            name='FQuestions',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='communication_ways',
        ),
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='communication_ways',
        ),
        migrations.AlterModelOptions(
            name='bannersectionone',
            options={'ordering': ('-created_at',), 'verbose_name': 'Small Banner', 'verbose_name_plural': 'Small Banners'},
        ),
        migrations.AlterModelOptions(
            name='sliderbannerimage',
            options={'verbose_name': 'Slider Banner', 'verbose_name_plural': 'Slider Banners'},
        ),
        migrations.RemoveField(
            model_name='bannersectionone',
            name='upload_at',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='upload_at',
        ),
        migrations.RemoveField(
            model_name='sliderbannerimage',
            name='upload_at',
        ),
        migrations.RemoveField(
            model_name='sliderlogo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sliderlogo',
            name='upload_at',
        ),
        migrations.AddField(
            model_name='bannersectionone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='communicationways',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AddField(
            model_name='communicationways',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='30 کاراکتر', max_length=30, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='sliderbannerimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='sliderbannerimage',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AddField(
            model_name='sliderlogo',
            name='brand_name',
            field=models.CharField(help_text='۲۵ کاراکتر', max_length=25, null=True, verbose_name='اسم برند'),
        ),
        migrations.AddField(
            model_name='sliderlogo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='sliderlogo',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AddField(
            model_name='sliderlogo',
            name='url_address',
            field=models.URLField(blank=True, null=True, verbose_name='Url Address'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='bannersectionone',
            name='img',
            field=models.ImageField(help_text='350 × 262 px', upload_to='banners', verbose_name='عکس بنر'),
        ),
        migrations.AlterField(
            model_name='bannersectionone',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='bannersectionone',
            name='url_address',
            field=models.URLField(blank=True, null=True, verbose_name='Url Address'),
        ),
        migrations.AlterField(
            model_name='communicationways',
            name='address',
            field=models.CharField(blank=True, help_text='150 کاراکتر', max_length=150, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='communicationways',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='communicationways',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='communicationways',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='companynumber',
            name='communication_ways',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_n', to='home_app.communicationways'),
        ),
        migrations.AlterField(
            model_name='companynumber',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره ثابت'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='status',
            field=models.BooleanField(default=True, help_text='در صورت غیرفعال کردن در وبسایت نمایش داده نمی شود'),
        ),
        migrations.AlterField(
            model_name='sliderbannerimage',
            name='img',
            field=models.ImageField(help_text='1079 × 378 px', upload_to='home_slider', verbose_name='عکس بنر'),
        ),
        migrations.AlterField(
            model_name='sliderbannerimage',
            name='sort_number',
            field=models.PositiveSmallIntegerField(default=1, unique=True, verbose_name='اولویت نمایش'),
        ),
        migrations.AlterField(
            model_name='sliderbannerimage',
            name='status',
            field=models.BooleanField(default=True, help_text='در صورت غیرفعال کردن در وبسایت نمایش داده نمی شود'),
        ),
        migrations.AlterField(
            model_name='sliderbannerimage',
            name='url_address',
            field=models.URLField(blank=True, null=True, verbose_name='Url Address'),
        ),
        migrations.AlterField(
            model_name='sliderlogo',
            name='img',
            field=models.ImageField(help_text='153 × 72 px', upload_to='logo_slider', verbose_name='تصویر لوگو'),
        ),
        migrations.DeleteModel(
            name='AboutUsFeature',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
