# Generated by Django 4.2.5 on 2024-01-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_remove_aboutusfeature_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannersectionone',
            name='img',
            field=models.ImageField(help_text='اندازه تصویر : 262 × 350', upload_to='banners', verbose_name='عکس بنر'),
        ),
        migrations.AlterField(
            model_name='sliderbannerimage',
            name='img',
            field=models.ImageField(help_text='اندازه تصویر : 378 × 1079', upload_to='home_slider', verbose_name='عکس بنر'),
        ),
        migrations.AlterField(
            model_name='sliderlogo',
            name='img',
            field=models.ImageField(help_text='اندازه تصویر : 284 × 600', upload_to='logo_slider', verbose_name='تصویر لوگو'),
        ),
    ]
