# Generated by Django 4.2.5 on 2023-10-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationways',
            name='address',
            field=models.CharField(blank=True, help_text='۱۵۰ کاراکتر مجاز است - optional', max_length=150, null=True, verbose_name='آدرس'),
        ),
    ]
