# Generated by Django 4.2.5 on 2024-02-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_alter_companynumber_province_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedboxtext',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='fixedboxtext',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
