# Generated by Django 4.2.5 on 2024-02-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_fixedboxtext_update_at_alter_fixedboxtext_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedboxtext',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='fixedboxtext',
            name='border_color',
        ),
        migrations.RemoveField(
            model_name='fixedboxtext',
            name='text_color',
        ),
        migrations.AddField(
            model_name='fixedboxtext',
            name='title',
            field=models.CharField(blank=True, help_text='۲۵ کاراکتر', max_length=25, null=True, verbose_name='عنوان'),
        ),
    ]
