# Generated by Django 4.2.5 on 2023-10-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_remove_sliderbannerimage_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannersectionone',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='bannersectionone',
            name='category_slug',
        ),
        migrations.RemoveField(
            model_name='bannersectiontwo',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='bannersectiontwo',
            name='category_slug',
        ),
        migrations.AddField(
            model_name='bannersectionone',
            name='url_address',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس URL'),
        ),
        migrations.AddField(
            model_name='bannersectiontwo',
            name='url_address',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس URL'),
        ),
    ]
