# Generated by Django 4.2.5 on 2023-11-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_sliderbannerimage_sort_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedBoxText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('status', models.BooleanField(default=True, help_text='درصورت غیرفعال کردن در سایت نمایش داده نمیشود', verbose_name='وضعیت نمایش')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'متن ثابت',
                'verbose_name_plural': 'متن های ثابت',
            },
        ),
    ]
