# Generated by Django 4.2.5 on 2023-11-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_fixedboxtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedboxtext',
            name='text',
            field=models.TextField(help_text='از نوشتن متن طولانی خودداری کنید', verbose_name='متن'),
        ),
    ]
