# Generated by Django 4.2.5 on 2023-11-08 14:51

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_alter_fixedboxtext_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedboxtext',
            name='background_color',
            field=colorfield.fields.ColorField(default='#0e1953', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='fixedboxtext',
            name='text_color',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='fixedboxtext',
            name='url',
            field=models.URLField(blank=True, help_text='optional - بک لینک متن', null=True),
        ),
    ]
