# Generated by Django 4.2.5 on 2023-11-08 15:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0010_fixedboxtext_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedboxtext',
            name='border_color',
            field=colorfield.fields.ColorField(default='#d90000', image_field=None, max_length=25, samples=None),
        ),
    ]
