# Generated by Django 4.2.5 on 2023-11-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_fixedboxtext_border_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderlogo',
            name='img',
            field=models.ImageField(help_text='حداقل اندازه تصویر 1280x452px یاشد', upload_to='logo_slider', verbose_name='تصویر لوگو'),
        ),
    ]
