# Generated by Django 4.2.5 on 2023-11-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_alter_sliderlogo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='فایل های pdf و png و jpg مجاز هستند', upload_to='uploaded_file', verbose_name='فایل')),
            ],
        ),
    ]
