# Generated by Django 4.2.5 on 2023-11-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0013_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='absolute_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='size',
            field=models.FloatField(default=0, help_text='برحسب کیلوبایت (KB) است'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(help_text='فایل های pdf و png و jpg مجاز هستند', upload_to='uploaded_file'),
        ),
    ]
